services:
    percona-entity:
        image: percona:5.7.35-centos
        container_name: cont-percona-entity
        restart: always
        networks:
            - network-entity
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: database-entity
            MYSQL_USER: user-entity
            MYSQL_PASSWORD: "123entity"
            MYSQL_RANDOM_ROOT_PASSWORD: 1
        volumes:
            - volume-entity:/var/lib/mysql

    phpmmyadmin-entity:
        image: phpmyadmin:latest
        container_name: cont-phpmyadmin-entity
        restart: always
        ports:
            - "8080:80"
        links:
            - percona-entity
        networks:
            - network-entity
        environment:
            - PMA_ARBITRARY=1
        depends_on:
            - percona-entity

networks:
    network-entity:
        driver: bridge

volumes:
    volume-entity:
        external: true
