services:
    percona-entity:
        image: percona:5.7.35-centos
        container_name: cont-percona-entity
        restart: always
        networks:
            - network-entity
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: database-entity
            MYSQL_USER: user-entity
            MYSQL_PASSWORD: "123entity"
            MYSQL_RANDOM_ROOT_PASSWORD: 1
        volumes:
            - volume-entity:/var/lib/mysql

    phpmmyadmin-entity:
        image: phpmyadmin:latest
        container_name: cont-phpmyadmin-entity
        restart: always
        ports:
            - "8080:80"
        links:
            - percona-entity
        networks:
            - network-entity
        environment:
            - PMA_ARBITRARY=1
        depends_on:
            - percona-entity

    sqlserver-entity:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: cont-sqlserver-entity
        restart: always
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=123entity
        networks:
            - network-entity

    oracle-express-entity:
        container_name: cont-oracle-express-entity
        build: 21.3.0/
        restart: always
        ports:
            - 1521:1521
        networks:
            - network-entity

networks:
    network-entity:
        driver: bridge

volumes:
    volume-entity:
        external: true
